#/bin/sh

export PYTHONPATH=$PYTHONPATH:./G0
export PYTHONPATH=$PYTHONPATH:./G1
export PYTHONPATH=$PYTHONPATH:./G2
export PYTHONPATH=$PYTHONPATH:./G3

export PYTHONPATH=$PYTHONPATH:./L0
export PYTHONPATH=$PYTHONPATH:./L1
export PYTHONPATH=$PYTHONPATH:./L2
export PYTHONPATH=$PYTHONPATH:./L3
export PYTHONPATH=$PYTHONPATH:./L4
export PYTHONPATH=$PYTHONPATH:./L5
export PYTHONPATH=$PYTHONPATH:./L6
export PYTHONPATH=$PYTHONPATH:./L7
export PYTHONPATH=$PYTHONPATH:./L8
export PYTHONPATH=$PYTHONPATH:./L9

export PYTHONPATH=$PYTHONPATH:./ui/form_main
export PYTHONPATH=$PYTHONPATH:./ui/form_fincomposition
export PYTHONPATH=$PYTHONPATH:./ui/form_finstruct

python3 -u gui_finmanager.py
