# КАТАЛОГ ПРОЕКТА: ФИНСОСТАВ
# 2023-12-03

CATEGORY   = "Категория"
FREQUENCY  = "Периодичность"
OBJECT_EXT = "Объект внешний"
OBJECT_INT = "Объект внутренний"
PRIORITY   = "Приоритет"
PROCESS    = "Процесс"

FINDESCRIPTION_CATEGORIES : list[str] = []
FINDESCRIPTION_CATEGORIES.append(CATEGORY)
FINDESCRIPTION_CATEGORIES.append(FREQUENCY)
FINDESCRIPTION_CATEGORIES.append(OBJECT_EXT)
FINDESCRIPTION_CATEGORIES.append(OBJECT_INT)
FINDESCRIPTION_CATEGORIES.append(PRIORITY)
FINDESCRIPTION_CATEGORIES.append(PROCESS)
